=== AstrorEnales/PubRDI/data/references/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://github.com/AstrorEnales/PubRDI/tree/master/data/references/schema.json",
  "title": "Publication",
  "description": "Information from a publication relevant to drug-remedy interactions",
  "type": "object",
  "properties": {
    "publication": {
      "type": "object",
      "description": "Reference of the publication",
      "properties": {
        "pmid": {
          "type": "integer",
          "description": "The PubMed ID of the publication"
        },
        "doi": {
          "type": "string",
          "description": "The DOI of the publication"
        },
        "citation": {
          "type": "string",
          "description": "The citation of the publication"
        }
      },
      "required": [
        "pmid",
        "citation"
      ]
    },
    "remedies": {
      "type": "array",
      "description": "TODO",
      "items": {
        "$ref": "#/definitions/remedy"
      }
    },
    "drugs": {
      "type": "array",
      "description": "TODO",
      "items": {
        "$ref": "#/definitions/drug"
      }
    },
    "compounds": {
      "type": "array",
      "description": "TODO",
      "items": {
        "$ref": "#/definitions/compound"
      }
    },
    "enzymes": {
      "type": "array",
      "description": "TODO",
      "items": {
        "$ref": "#/definitions/enzyme"
      }
    },
    "transporter": {
      "type": "array",
      "description": "TODO",
      "items": {
        "$ref": "#/definitions/transporter"
      }
    },
    "remedy-compounds": {
      "type": "array",
      "description": "TODO",
      "items": {
        "$ref": "#/definitions/remedy-compound-link"
      }
    },
    "drug-compounds": {
      "type": "array",
      "description": "TODO",
      "items": {
        "$ref": "#/definitions/drug-compound-link"
      }
    },
    "processes": {
      "type": "array",
      "description": "TODO",
      "items": {
        "$ref": "#/definitions/process"
      }
    },
    "studies": {
      "type": "array",
      "description": "TODO",
      "items": {
        "$ref": "#/definitions/study"
      }
    }
  },
  "definitions": {
    "remedy": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "description": "TODO"
        },
        "name": {
          "type": "string",
          "description": "TODO"
        },
        "xrefs": {
          "type": "array",
          "description": "TODO",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "drug": {
      "type": "object",
      "description": "TODO",
      "properties": {
        "id": {
          "type": "integer",
          "description": "TODO"
        },
        "name": {
          "type": "string",
          "description": "TODO"
        },
        "xrefs": {
          "type": "array",
          "description": "TODO",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "compound": {
      "type": "object",
      "description": "TODO",
      "properties": {
        "id": {
          "type": "integer",
          "description": "TODO"
        },
        "name": {
          "type": "string",
          "description": "TODO"
        },
        "xrefs": {
          "type": "array",
          "description": "TODO",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "enzyme": {
      "type": "object",
      "description": "TODO",
      "properties": {
        "id": {
          "type": "integer",
          "description": "TODO"
        },
        "name": {
          "type": "string",
          "description": "TODO"
        },
        "xrefs": {
          "type": "array",
          "description": "TODO",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "transporter": {
      "type": "object",
      "description": "TODO",
      "properties": {
        "id": {
          "type": "integer",
          "description": "TODO"
        },
        "name": {
          "type": "string",
          "description": "TODO"
        },
        "xrefs": {
          "type": "array",
          "description": "TODO",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "remedy-compound-link": {
      "type": "object",
      "description": "TODO",
      "properties": {
        "remedy-id": {
          "type": "integer",
          "description": "TODO"
        },
        "compound-id": {
          "type": "integer",
          "description": "TODO"
        }
      }
    },
    "drug-compound-link": {
      "type": "object",
      "description": "TODO",
      "properties": {
        "drug-id": {
          "type": "integer",
          "description": "TODO"
        },
        "compound-id": {
          "type": "integer",
          "description": "TODO"
        }
      }
    },
    "process": {
      "type": "object",
      "description": "TODO",
      "properties": {
        "id": {
          "type": "integer",
          "description": "TODO"
        },
        "type": {
          "type": "string",
          "description": "TODO"
        },
        "enzyme-id": {
          "type": "integer",
          "description": "TODO"
        },
        "transporter-id": {
          "type": "integer",
          "description": "TODO"
        },
        "substrates": {
          "type": "array",
          "description": "TODO",
          "items": {
            "type": "object",
            "properties": {
              "compound-id": {
                "type": "integer",
                "description": "TODO"
              }
            }
          }
        },
        "products": {
          "type": "array",
          "description": "TODO",
          "items": {
            "type": "object",
            "properties": {
              "compound-id": {
                "type": "integer",
                "description": "TODO"
              }
            }
          }
        }
      }
    },
    "study": {
      "type": "object",
      "description": "TODO",
      "properties": {
        "id": {
          "type": "integer",
          "description": "TODO"
        },
        "type": {
          "type": "string",
          "description": "TODO"
        },
        "subject-group": {
          "type": "object",
          "description": "TODO",
          "properties": {
            "total": {
              "type": "integer",
              "description": "TODO",
              "minimum": 0
            },
            "male": {
              "type": "integer",
              "description": "TODO",
              "minimum": 0
            },
            "female": {
              "type": "integer",
              "description": "TODO",
              "minimum": 0
            },
            "age-min": {
              "type": "integer",
              "description": "TODO",
              "minimum": 0
            },
            "age-max": {
              "type": "integer",
              "description": "TODO",
              "minimum": 0
            },
            "age-median": {
              "type": "number",
              "description": "TODO",
              "minimum": 0
            }
          }
        }
      }
    }
  }
}

=== AstrorEnales/PubRDI/data/references/pmid_11180034/data.json
{
  "publication": {
    "pmid": 11180034,
    "doi": "10.1067/mcp.2001.113185",
    "citation": "Malhotra, S. (2001). Seville orange juice-felodipine interaction: Comparison with dilute grapefruit juice and involvement of furocoumarins. Clinical Pharmacology & Therapeutics, 69(1), 14â€“23."
  },
  "remedies": [
    {
      "id": 0,
      "name": "Seville orange juice",
      "xrefs": [
        "ITIS:825215"
      ]
    }
  ],
  "drugs": [
    {
      "id": 0,
      "name": "Felodipine",
      "xrefs": [
        "DRUGBANK:DB01023",
        "DRUGCENTRAL:1142"
      ]
    }
  ],
  "compounds": [
    {
      "id": 0,
      "name": "Felodipine",
      "xrefs": [
        "HMDB:HMDB0015158",
        "PUBCHEM:CID3333",
        "UNII:OL961R6O2C",
        "CAS:72509-76-3"
      ]
    }
  ],
  "enzymes": [],
  "transporter": [],
  "remedy-compounds": [],
  "drug-compounds": [
    {
      "drug-id": 0,
      "compound-id": 0
    }
  ],
  "processes": [],
  "studies": []
}

=== AstrorEnales/PubRDI/data/references/pmid_17215845/data.json
{
  "publication": {
    "pmid": 17215845,
    "doi": "10.1038/sj.clpt.6100056",
    "citation": "Glaeser, H., Bailey, D. G., Dresser, G. K., Gregor, J. C., Schwarz, U. I., McGrath, J. S., … Kim, R. B. (2007). Intestinal Drug Transporter Expression and the Impact of Grapefruit Juice in Humans. Clinical Pharmacology & Therapeutics, 81(3), 362–370."
  },
  "remedies": [
    {
      "id": 0,
      "name": "Grapefruit juice",
      "xrefs": [
        "ITIS:28887"
      ]
    }
  ],
  "drugs": [],
  "compounds": [],
  "enzymes": [],
  "transporter": [],
  "remedy-compounds": [],
  "drug-compounds": [],
  "processes": [],
  "studies": []
}

=== AstrorEnales/PubRDI/data/references/pmid_12095536/data.json
{
  "publication": {
    "pmid": 12095536,
    "doi": "10.1016/S0024-3205(02)01799-X",
    "citation": "Di Marco MP, et al. The effect of grapefruit juice and seville orange juice on the pharmacokinetics of dextromethorphan: the role of gut CYP3A and P-glycoprotein. Life Sci. 2002;71(10):1149-60."
  },
  "remedies": [
    {
      "id": 0,
      "name": "Grapefruit juice",
      "xrefs": [
        "ITIS:28887"
      ]
    },
    {
      "id": 1,
      "name": "Seville orange juice",
      "xrefs": [
        "ITIS:825215"
      ]
    }
  ],
  "drugs": [
    {
      "id": 0,
      "name": "Dextromethorphan",
      "xrefs": [
        "DRUGBANK:DB00514",
        "DRUGCENTRAL:842"
      ]
    }
  ],
  "compounds": [
    {
      "id": 0,
      "name": "Dextromethorphan",
      "xrefs": [
        "HMDB:HMDB0001920",
        "PUBCHEM:CID5362449",
        "PUBCHEM:CID5360696",
        "UNII:7355X3ROTS",
        "CAS:125-71-3"
      ]
    },
    {
      "id": 1,
      "name": "3-methoxymorphinan",
      "xrefs": [
        "HMDB:HMDB0014045",
        "PUBCHEM:CID6603912",
        "DRUGBANK:DBMET00225"
      ]
    },
    {
      "id": 2,
      "name": "dextrorphan",
      "xrefs": [
        "HMDB:HMDB0060552",
        "PUBCHEM:CID5360697",
        "DRUGBANK:DBMET00224"
      ]
    },
    {
      "id": 3,
      "name": "3-hydroxymorphinan",
      "xrefs": [
        "PUBCHEM:CID11791385",
        "UNII:AG3VB17119",
        "DRUGBANK:DBMET01318"
      ]
    }
  ],
  "enzymes": [
    {
      "id": 0,
      "name": "CYP3A",
      "xrefs": []
    },
    {
      "id": 1,
      "name": "CYP2D6",
      "xrefs": [
        "UNIPROT:P10635"
      ]
    }
  ],
  "transporter": [
    {
      "id": 0,
      "name": "P-glycoprotein",
      "xrefs": [
        "UNIPROT:P08183"
      ]
    }
  ],
  "remedy-compounds": [],
  "drug-compounds": [
    {
      "drug-id": 0,
      "compound-id": 0
    }
  ],
  "processes": [
    {
      "id": 0,
      "type": "reaction",
      "substrates": [
        {
          "compound-id": 0
        }
      ],
      "enzyme-id": 0,
      "products": [
        {
          "compound-id": 1
        }
      ]
    },
    {
      "id": 1,
      "type": "reaction",
      "substrates": [
        {
          "compound-id": 0
        }
      ],
      "enzyme-id": 1,
      "products": [
        {
          "compound-id": 2
        }
      ]
    },
    {
      "id": 2,
      "type": "reaction",
      "substrates": [
        {
          "compound-id": 1
        }
      ],
      "enzyme-id": 1,
      "products": [
        {
          "compound-id": 3
        }
      ]
    },
    {
      "id": 3,
      "type": "reaction",
      "substrates": [
        {
          "compound-id": 2
        }
      ],
      "enzyme-id": 0,
      "products": [
        {
          "compound-id": 3
        }
      ]
    },
    {
      "id": 4,
      "type": "transport",
      "substrates": [
        {
          "compound-id": 0
        }
      ],
      "transporter-id": 0,
      "products": [
        {
          "compound-id": 0
        }
      ]
    }
  ],
  "studies": [
    {
      "id": 0,
      "type": "clinical study",
      "subject-group": {
        "total": 11,
        "male": 6,
        "female": 5,
        "age-min": 14,
        "age-max": 43,
        "age-median": 32
      }
    }
  ]
}

=== AstrorEnales/PubRDI/data/references/pmid_10871299/data.json
{
  "publication": {
    "pmid": 10871299,
    "citation": "Obach RS. Inhibition of human cytochrome P450 enzymes by constituents of St. John's Wort, an herbal preparation used in the treatment of depression. J Pharmacol Exp Ther. 2000;294(1):88-95."
  },
  "remedies": [
    {
      "id": 0,
      "name": "St John's wort",
      "xrefs": [
        "ITIS:21454"
      ]
    }
  ],
  "drugs": [],
  "compounds": [],
  "enzymes": [],
  "transporter": [],
  "remedy-compounds": [],
  "drug-compounds": [],
  "processes": [],
  "studies": []
}

=== AstrorEnales/PubRDI/data/references/pmid_25640094/data.json
{
  "publication": {
    "pmid": 25640094,
    "doi": "10.11622/smedj.2015004",
    "citation": "Chua, Y., Ang, X., Zhong, X., & Khoo, K. (2015). Interaction between warfarin and Chinese herbal medicines. Singapore Medical Journal, 56(1), 11â€“18."
  },
  "remedies": [
    {
      "id": 0,
      "name": "Danshen",
      "xrefs": []
    },
    {
      "id": 1,
      "name": "Ginkgo",
      "xrefs": [
        "ITIS:183269"
      ]
    },
    {
      "id": 2,
      "name": "Dong quai",
      "xrefs": []
    },
    {
      "id": 3,
      "name": "American ginseng",
      "xrefs": [
        "ITIS:29399"
      ]
    },
    {
      "id": 4,
      "name": "Safflower",
      "xrefs": [
        "ITIS:501305"
      ]
    },
    {
      "id": 5,
      "name": "Peach kernel",
      "xrefs": [
        "ITIS:24765"
      ]
    },
    {
      "id": 6,
      "name": "Licorice",
      "xrefs": [
        "ITIS:26718"
      ]
    },
    {
      "id": 7,
      "name": "Asian ginseng",
      "xrefs": [
        "ITIS:505938"
      ]
    },
    {
      "id": 8,
      "name": "Lycium",
      "xrefs": [
        "ITIS:503599"
      ]
    },
    {
      "id": 9,
      "name": "Ginger",
      "xrefs": [
        "ITIS:42402"
      ]
    },
    {
      "id": 10,
      "name": "Notoginseng",
      "xrefs": []
    }
  ],
  "drugs": [
    {
      "id": 0,
      "name": "Warfarin",
      "xrefs": [
        "DRUGBANK:DB00682"
      ]
    }
  ],
  "compounds": [],
  "enzymes": [],
  "transporter": [],
  "remedy-compounds": [],
  "drug-compounds": [],
  "processes": [],
  "studies": []
}

=== AstrorEnales/PubRDI/data/references/pmid_15089812/data.json
{
  "publication": {
    "pmid": 15089812,
    "doi": "10.1111/j.1365-2125.2003.02051.x",
    "citation": "Jiang, X., Williams, K. M., Liauw, W. S., Ammit, A. J., Roufogalis, B. D., Duke, C. C., … McLachlan, A. J. (2004). Effect of St John’s wort and ginseng on the pharmacokinetics and pharmacodynamics of warfarin in healthy subjects. British Journal of Clinical Pharmacology, 57(5), 592–599."
  },
  "remedies": [
    {
      "id": 0,
      "name": "St John's wort",
      "xrefs": [
        "ITIS:21454"
      ]
    }
  ],
  "drugs": [
    {
      "id": 0,
      "name": "S-Warfarin",
      "xrefs": [
        "DRUGBANK:DB14055"
      ]
    },
    {
      "id": 1,
      "name": "R-Warfarin",
      "xrefs": [
        "DRUGBANK:DB08496"
      ]
    }
  ],
  "compounds": [],
  "enzymes": [],
  "transporter": [],
  "remedy-compounds": [],
  "drug-compounds": [],
  "processes": [],
  "studies": [
    {
      "type": "clinical study",
      "subject-group": {
        "total": 12,
        "male": 12,
        "female": 0
      }
    }
  ]
}
